apiVersion: v1
kind: Service
metadata:
  name: aspnet-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80 # Replace this with the port your container is listening on
  selector:
    app: aspnet-app # This should match the label of your pods
